### ISSUE TITLE
TheQtCompany/qt5

### ISSUE THREAD

**Issue by photex** [LoopPerfect/buckaroo-wishlist#61]
http://qt.io

I realize this is perhaps complicated to achieve. I wouldn't expect to build qt from source, but perhaps use a specified build.

I suppose this would also not be very useful without first contributing some qt support to Buck (handling MOC, UIC, and RCC needs).

**Comment by njlr** [comment]
This is a tricky one, but I agree that it should be included! 

Taking a look at the source, it has lots of dependencies: https://github.com/qt/qtbase/tree/dev/src/3rdparty 

We would also need to set the preprocessor to use the Qt one. This is something Buck supports via `.buckconfig`. https://stackoverflow.com/questions/3588154/how-usable-is-qt-without-its-preprocessing-step

Since this is such a big dependency, I can't give an estimate for a proper port yet.

What I would suggest for now is to configure Buck to pick up the system's installation of Qt. 

 - Install Qt on your system, e.g. `brew install qt` using Homebrew
 - Set the preprocessor and linker flags of you app

I have created an example here: [https://github.com/njlr/buck-qt-workaround](https://github.com/njlr/buck-qt-workaround). It only works for macOS; if you need it extended to other platforms we can help with that. 

Buckaroo packages should have no problems integrating with this setup. Hope that helps!
