### ISSUE TITLE
davisking/dlib

### ISSUE THREAD

**Issue by voldyman** [LoopPerfect/buckaroo-wishlist#65]
[dlib](https://github.com/davisking/dlib) :)

**Comment by njlr** [comment]
Hi @voldyman! 

Looks like an easy enough port; I'll take a look!

**Comment by njlr** [comment]
I have completed a basic port of dlib ([PR](https://github.com/LoopPerfect/buckaroo-recipes/pull/70)). 

dlib has two compilation modes, switched using `-DDLIB_ISO_CPP_ONLY`. The current package has this enabled, so only the core functionality of dlib is provided. If you need more functionality, let me know and I can take another look. 

Anyway, to install dlib: 

```bash= 
buckaroo upgrade
buckaroo install davisking/dlib 
```

**Comment by voldyman** [comment]
thanks for the quick turnaround time, i am trying to fix another issue right now

```
└─> buckaroo update
Exception in thread "main" java.lang.NullPointerException
	at com.loopperfect.buckaroo.Main.main(Main.java:55)```

as soon as i fix it i'll try use dlib from buckaroo and close this issue. 👍

**Comment by njlr** [comment]
The server components sit outside of the `DLIB_ISO_CPP_ONLY` components. See [here](https://github.com/davisking/dlib/blob/master/dlib/all/source.cpp). 

Do you know which parts you require?

**Comment by voldyman** [comment]
Yup, i use `server_http`,  `image_processing` & `gui_widgets`

**Comment by njlr** [comment]
OK, should be viable. Are you on Linux? These components will be platform-specific so I will port your platform first.

**Comment by voldyman** [comment]
I am on mac OS

**Comment by njlr** [comment]
Great, me too. 

I managed to get the full build of dlib working on macOS. [Here](https://github.com/njlr/dlib/blob/master/BUCK) is the `BUCK` file. 

You can update your cookbook using: 

```bash=
buckaroo upgrade
```

Since the full dlib uses X11, you will need to link some dynamic libraries into your project. They are not linked into the Buckaroo dlib package because that might break reproducibility. 

This is how you can do this in your project's `BUCK` file: 

```python=
macos_linker_flags = [
  '-L/usr/X11/lib',
  '-lX11',
]

cxx_binary(
  name = 'app',
  srcs = [
    'main.cpp',
  ],
  compiler_flags = [
    '-std=c++11',
  ],
  platform_linker_flags = [
    ('default', macos_linker_flags),
    ('^macos.*', macos_linker_flags),
  ],
  deps = BUCKAROO_DEPS,
)
```

You can see this in action in [the examples that I ported to Buck](https://github.com/njlr/dlib/blob/master/examples/BUCK).
