### ISSUE TITLE
abseil/abseil-cpp

### ISSUE THREAD

**Issue by krzysztofwos** [LoopPerfect/buckaroo-wishlist#78]
Abseil is built with Bazel which looks just like Buck if you squint your eyes hard enough. Should be easy to port.

**Comment by njlr** [comment]
Yes indeed! 

The challenge is that Abseil has a ["live at head" philosophy](https://abseil.io/about/philosophy#we-recommend-that-you-choose-to-live-at-head). Basically, they are taking the [latest commit as a dependency](https://github.com/abseil/abseil-cpp/blob/master/WORKSPACE#L17) using Bazel. This means they can release fast, but also that code is unstable. As a result, they will not provide sem-ver releases that we can package. Buckaroo takes a different approach, because we want things to be more stable, so it does not support this use-case. 

Perhaps we should create our own versions? What do you think?

cc @nikhedonia

**Comment by nikhedonia** [comment]
In short term we can make our own versions.
Mid-term buckaroo should accept hashes (and hash ranges?) as versions.

We could also have travis try to build every commit and run tests.
If it the tests succeed bump the minor version number and on failure
(manually) add a new testsuite and bump the major version number. Any
volunteers ?



<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

On 26 October 2017 at 12:55, njlr <notifications@github.com> wrote:

> Yes indeed!
>
> The challenge is that Abseil has a "live at head" philosophy
> <https://mailtrack.io/trace/link/670f5d214e895603f78d3eb3a91ef50b13978047?url=https%3A%2F%2Fabseil.io%2Fabout%2Fphilosophy%23we-recommend-that-you-choose-to-live-at-head&userId=931501&signature=b2fc9ccff8ac13b5>.
> Basically, they are taking the latest commit as a dependency
> <https://mailtrack.io/trace/link/9be6baa4340fec86989c56d4d1ed419a2b60bb38?url=https%3A%2F%2Fgithub.com%2Fabseil%2Fabseil-cpp%2Fblob%2Fmaster%2FWORKSPACE%23L17&userId=931501&signature=f06402d21c43edc2>
> using Bazel. This means they can release fast, but also that code is
> unstable. As a result, they will not provide sem-ver releases that we can
> package. Buckaroo takes a different approach, because we want things to be
> more stable, so it does not support this use-case.
>
> Perhaps we should create our own versions? What do you think?
>
> cc @nikhedonia
> <https://mailtrack.io/trace/link/c19f345d91414877cd7f78e453a56f1c28a3d9c2?url=https%3A%2F%2Fgithub.com%2Fnikhedonia&userId=931501&signature=5df41a9799494d30>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/8771dc4f0c4681094c277eda615db9b842eb662f?url=https%3A%2F%2Fgithub.com%2FLoopPerfect%2Fbuckaroo-wishlist%2Fissues%2F78%23issuecomment-339642043&userId=931501&signature=59c943aeb341b51d>,
> or mute the thread
> <https://mailtrack.io/trace/link/d5b81e7c22a2130a44fa3a780ae03cf88a9c04bd?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEdCZ41VGp6iq9KN9G4mmAXkajK7toviks5swHM3gaJpZM4QHain&userId=931501&signature=6aa9fc19ff4cb325>
> .
>



-- 
Regards,

Gaetano Checinski
Founder of Loopperfect
https://loopperfect.com
<https://mailtrack.io/trace/link/a9e884992800d4fbde379e15af9432eb029a379d?url=https%3A%2F%2Floopperfect.com&userId=931501&signature=867ff08aa9ad28de>
https://buckaroo.pm
<https://mailtrack.io/trace/link/d5f2d5914da4cd896f98d53d7d617f53349e2d24?url=https%3A%2F%2Fbuckaroo.pm&userId=931501&signature=d0f8c5d64857b875>

**Comment by krzysztofwos** [comment]
Hmm... it's indeed a pickle. It would seem that one possible "mapping" to sem-ver would be to bump the major version each time they push code to the repo and pin that version to that commit? I mean a better approach would be to look through the changes and figure out whether to bump major, minor, or patch, but if that's too much to ask of the recipe maintainer. So a pragmatic approach would be to have a script that
- Pulls from the repo.
- Checks if there's anything new. If there isn't, call it a day.
- Otherwise, creates a new release, bumps the major number, updates whatever needs updating.
Since each push to Abseil is potentially breaking, users could choose whether they want to update or not.
So the last question is who keeps stuff up to date? If you can automate all of it, a cron job, or a user?

**Comment by krzysztofwos** [comment]
@nikhedonia since we don't know what goes in, wouldn't it be more appropriate to bump the major? Basically just have major versions, e.g. v1, v2, ...?

**Comment by nikhedonia** [comment]
Yeah probably. Your suggestion is definitely always semantically correct
because incrementing a major version number makes no guarantees about the
API and I think this matches the "moving fast" ideology.

However, If someone would define a mapping between a testsuite and a
version number than we could provide more granular version numbers. I
understand though this would require work and might be error prone.


‌
<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

On 26 October 2017 at 13:18, Krzysztof Woś <notifications@github.com> wrote:

> @nikhedonia
> <https://mailtrack.io/trace/link/f30d1f50d609e75b33d2121038424803278edcec?url=https%3A%2F%2Fgithub.com%2Fnikhedonia&userId=931501&signature=8731881721e1b24a>
> since we don't know what goes in, wouldn't it be more appropriate to bump
> the major? Basically just have major versions, e.g. v1, v2, ...?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/2198bec62c4f652927700bae62fd28234914ce0d?url=https%3A%2F%2Fgithub.com%2FLoopPerfect%2Fbuckaroo-wishlist%2Fissues%2F78%23issuecomment-339647272&userId=931501&signature=17f1293c72bcc797>,
> or mute the thread
> <https://mailtrack.io/trace/link/812dea195dfc74e947ac1e93fe1a53115246cdde?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEdCZyIOuUGmiVp-d43G8eebmzfh1b7nks5swHiLgaJpZM4QHain&userId=931501&signature=16586f44c8a71bea>
> .
>



-- 
Regards,

Gaetano Checinski
Founder of Loopperfect
https://loopperfect.com
<https://mailtrack.io/trace/link/177394cf38ee943d6abc55880a444e28ff005ee6?url=https%3A%2F%2Floopperfect.com&userId=931501&signature=3d79dbe606a797c3>
https://buckaroo.pm
<https://mailtrack.io/trace/link/cfc5093e041085777f4d4312a90bf5dd0de08450?url=https%3A%2F%2Fbuckaroo.pm&userId=931501&signature=e670a6656739ba9e>

**Comment by nikhedonia** [comment]
@njlr How about implementing auto versioning in buckaroo ?

One quick way could be to do the following:
- if no version exists do
- get commit log of repo
- count commits until given hash
- use count as version number

**Comment by njlr** [comment]
My view is: 

 - Short term, we create some versions ourselves. Pick a recent commit that passes all tests and package it as `v0.1.0`. This allows people to get up and running ASAP. 
 - Long term, we should allow you to depend on a Git URL + branch directly. Basically every commit hash is considered a version and we ensure that all dependencies use the same commit. This is stable because we have a lock file inside of each project. If the latest commit is broken, then we can introduce ranges, as you suggested.

**Comment by njlr** [comment]
PR for cctz `v2.1.0`, which is required by Abseil: https://github.com/LoopPerfect/buckaroo-recipes/pull/106

Buck build of Abseil: https://github.com/njlr/abseil-cpp/tree/improvement/buck-build

**Comment by njlr** [comment]
Since Buckaroo v2 we support dependencies on branches, meaning we can support Abseil properly!

You can install [the package](https://github.com/buckaroo-pm/abseil-cpp) with: 

```bash
$ buckaroo add github.com/buckaroo-pm/abseil-cpp
```
